name: Presubmit.ai

permissions:
  contents: read
  pull-requests: write
  issues: write

on:
  push:
  pull_request:
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: presubmit/ai-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LLM_API_KEY: ${{ secrets.AI_KEY }}
        with:
          llm_model: "gpt-4o-mini"
